// Pure verifier + binding for the installer checksum manifest.
//
// release/checksums.json (generated by gen-installer-checksums.mjs) records, for
// each installer .exe, its byte length and sha256. The release contract must
// prove these still describe the bytes ACTUALLY on disk — a stale manifest that
// disagrees with the binary is exactly the incident this closes ("binary /
// attestation / checksums disagree"). This module is pure: callers hand it the
// manifest and the freshly-measured installer facts; it returns a verdict.

import { createHash } from 'node:crypto'

/** sha256 hex of a buffer. */
export function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex')
}

/** Parse `Setup <x.y.z>` version out of an installer file name, or null. */
export function versionFromInstallerName(name) {
  const m = /(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)\.exe$/i.exec(name)
  return m ? m[1] : null
}

/**
 * Verify a checksum manifest against measured installers.
 *   manifest   : { installers: [{ name, bytes, sha256 }] } | null
 *   installers : [{ name, bytes, sha256 }]  (freshly measured from disk)
 * Returns { ok, errors[] }. Fails closed: a missing manifest, a manifest entry
 * with no matching binary, a binary with no manifest entry, or any byte/hash
 * disagreement is an error.
 */
export function verifyChecksums(manifest, installers) {
  const errors = []
  if (!manifest || !Array.isArray(manifest.installers) || manifest.installers.length === 0) {
    return { ok: false, errors: ['checksums.json missing or empty'] }
  }
  const byName = new Map(manifest.installers.map(e => [e.name, e]))
  const seen = new Set()
  for (const bin of installers) {
    const rec = byName.get(bin.name)
    seen.add(bin.name)
    if (!rec) {
      errors.push(`installer ${bin.name} has no checksum entry`)
      continue
    }
    if (rec.sha256 !== bin.sha256) {
      errors.push(`${bin.name}: checksum sha256 ${short(rec.sha256)} != actual ${short(bin.sha256)}`)
    }
    if (Number(rec.bytes) !== Number(bin.bytes)) {
      errors.push(`${bin.name}: checksum bytes ${rec.bytes} != actual ${bin.bytes}`)
    }
  }
  for (const rec of manifest.installers) {
    if (!seen.has(rec.name)) errors.push(`checksum entry ${rec.name} has no matching binary on disk`)
  }
  return { ok: errors.length === 0, errors }
}

function short(h) {
  return typeof h === 'string' ? h.slice(0, 12) : String(h)
}
