// verify:plugin — proves the shipped business-shell Desktop plugin is loadable by
// the REAL target Hermes, not by any local reproduction of the loader.
//
// Two anchors, both derived from official source:
//   1. A checked-in contract snapshot (scripts/hermes-desktop-contract.json)
//      generated by gen-hermes-contract.mjs from installed Hermes 0.19.1 source
//      — the network-free reference used on clean build machines.
//   2. The installed Hermes Desktop source itself, resolved via
//      electron/paths.cjs (hermesHome). When present it is authoritative: the
//      version must be in range and every SDK symbol / host door / PluginContext
//      method / contribution area / loader+discovery fact our plugin.js relies on
//      must exist in it, or this FAILS CLOSED.
//
// It NEVER cites scripts/lib/probes/hermes/plugin-*.mjs (the fast unit contract
// harness) as evidence of loading. With --release, the installed real source is
// mandatory and must match the snapshot byte-for-byte (sha256), so a release can
// never be cut against drifted or absent Hermes source.

import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { HERMES_COMPAT_RANGE, SDK_SYMBOLS } from './plugin-sdk-contract.mjs'
import {
  CONTRACT_FILES,
  checkRequirements,
  contractFilePath,
  extractPluginRequirements,
  fileSha256,
  readContractSources,
  readInstalledVersion,
  versionInRange
} from './lib/hermes-desktop-contract.mjs'

const releaseMode = process.argv.includes('--release')
const require = createRequire(import.meta.url)
const repoRoot = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const rel = p => path.join(repoRoot, p)
const { hermesHome } = require(rel('electron/paths.cjs'))

const source = readFileSync(rel('hermes-plugin/business-shell/plugin.js'), 'utf8')
const bootstrapSkill = readFileSync(rel('hermes-plugin/business-shell/skills/business-bootstrap/SKILL.md'), 'utf8')
const snapshot = JSON.parse(readFileSync(rel('scripts/hermes-desktop-contract.json'), 'utf8'))
const failures = []

// ---- 1. Structural plugin contract (static) ---------------------------------
if (!source.includes("from '@hermes/plugin-sdk'")) failures.push('missing official @hermes/plugin-sdk import')
if (!source.includes("id: 'business-shell'")) failures.push('plugin id is missing')
if (!source.includes('ROUTES_AREA')) failures.push('route contribution is missing')
if (!source.includes('SIDEBAR_NAV_AREA')) failures.push('sidebar contribution is missing')
if (!source.includes('business-bootstrap')) failures.push('guided first-run Skill is not referenced')
if (source.match(/from ['"](@\/|electron|fs|node:)/)) failures.push('plugin imports a forbidden module')
if (/<[A-Z][A-Za-z]*[ >]/.test(source)) failures.push('disk plugin contains JSX, which Hermes does not compile')
if (!bootstrapSkill.includes('name: business-bootstrap')) failures.push('business-bootstrap Skill metadata is missing')
if (!bootstrapSkill.includes('Ask one question at a time')) failures.push('business-bootstrap lacks progressive questions')
if (!bootstrapSkill.includes('Never request API keys')) failures.push('business-bootstrap lacks secret-handling rules')
if (!bootstrapSkill.includes('Recommend one connection')) failures.push('business-bootstrap lacks connection guidance')

// ---- 2. Live plugin requirements vs the pinned snapshot ---------------------
const req = extractPluginRequirements(source)
const covered = (kind, values) => {
  const pinned = new Set(snapshot.requirements[kind] || [])
  for (const value of values) {
    if (!pinned.has(value)) {
      failures.push(`plugin relies on ${kind} "${value}" not covered by the pinned contract; regenerate scripts/hermes-desktop-contract.json`)
    }
  }
}
covered('sdkSymbols', req.sdkSymbols)
covered('hostMembers', req.hostMembers)
covered('ctxMethods', req.ctxMethods)
covered('areas', req.areas)
// Cross-check the long-standing SDK_SYMBOLS pin still lists every imported symbol.
for (const symbol of req.sdkSymbols) {
  if (!SDK_SYMBOLS.includes(symbol)) failures.push(`plugin imports ${symbol}, absent from the pinned ${HERMES_COMPAT_RANGE} SDK contract`)
}

// ---- 3. Installed real Hermes source (authoritative when present) -----------
const home = hermesHome()
const version = readInstalledVersion(home)
if (version) {
  if (!versionInRange(version, HERMES_COMPAT_RANGE)) {
    failures.push(`installed Hermes ${version} is outside the supported range ${HERMES_COMPAT_RANGE}`)
  } else {
    const sources = readContractSources(home)
    failures.push(...checkRequirements(req, sources))
    if (releaseMode) {
      for (const [relPath, meta] of Object.entries(snapshot.sourceFiles)) {
        let actual = null
        try { actual = fileSha256(contractFilePath(home, meta.key)) } catch { /* missing */ }
        if (actual !== meta.sha256) {
          failures.push(`release: installed ${relPath} sha256 ${actual || 'unreadable'} != snapshot ${meta.sha256}; regenerate the contract from the target release source`)
        }
      }
    }
    console.log(`Verified against installed Hermes ${version} Desktop source (${Object.keys(CONTRACT_FILES).length} contract files).`)
  }
} else if (releaseMode) {
  failures.push(`release: no installed Hermes Desktop source under ${home}; run installer/bootstrap to acquire the official release source before packaging`)
} else {
  console.log(`Installed Hermes source absent; validated against the checked-in real-source snapshot for ${snapshot.generatedFrom.hermesVersion} (contract ${HERMES_COMPAT_RANGE}). This is the pinned contract, not a loader reproduction.`)
}

if (failures.length) {
  console.error(failures.map(item => `- ${item}`).join('\n'))
  process.exit(1)
}
console.log('Desktop plugin contract checks passed.')
